# АнДан: `import` – использование невстроенных функций и `numpy` – удобной математики

<div class="alert alert-block alert-info">
❗Всё это (<code>import</code>, <code>numpy</code>) <b>нельзя</b> использовать на экзамене по Python'у.
    Можно только на экзамене по Анализу данных.
</div>

Питон не включает в себя всё, что возможно придумать.

Кому-то нужно считать статистику, кому-то — сделать веб-сайт для своего магазина, а кому-то —  (ух!) строить неройнные сети.
    Для каждой из этих задач нужны совершенно разные программы.
    Поскольку это **задачи** достаточно **частые**, то **их кто-то уже решал**.

И действительно, немало сторонних разработчиков пишут малые (пакеты) или большие (библиотеки) программы для решения каких-то определённых задач, и делают их общедоступными (спасибо им!).

Что очень нужно нам, это удобно считать статистику.
    (А позже, возможно, также аккуратно делить русский текст на предложения и слова.)
    Оказывается, для этого тоже есть программы!    

## `numpy`

Ключевое в использовании сторонних пакетов это инструкция `import`.

Сразу попробуйте импортировать `numpy` – если у вас `python` и `jupyter` установлены через `Anaconda`, то `numpy` тоже будет уже установлен.

* *если не сработало, [перейдите сюда, к пункту "установка"](#install-numpy)*

In [137]:
import numpy

numbers = [4, 5, 10, 25]
print(numpy.mean(numbers))
print(numpy.max(numbers))

11.0
25


In [133]:
print(numpy.mean([4, 5, 10, 25]))

11.0


конечно, среднее можно было посчитать иначе:

In [138]:
mean = sum(numbers) / len(numbers)
print(mean)

11.0


In [6]:
# (переменная, для иллюстрации)
numpy.pi

3.141592653589793

Что произошло?

Мы попросили `python` прочитать весь код пакета `numpy` и запомнить функции и переменные, которые там записаны.
    Теперь мы можем к ним обращаться в таком виде: `<имя_пакета><ТОЧКА><имя_функции_или_переменной>`.

Выше мы посчитали для списка целых чисел `numbers` его среднее (функцией `numpy.mean` с этим списком как аргументом) и максимальное число в нём (функцией `numpy.max` с этим списком как аргументом).

Ниже мы вывели значение переменной `pi` из пакета `numpy`.

Обратите внимание, что функция, считающая максимум называется так же, как встроенная функция `python`! Ровно поэтому, чтобы `python` чётко понимал, какую именно функцию (или переменную) мы хотим использовать, и нужно писать `<имя_пакета><ТОЧКА><имя_функции_или_переменной>` с указанием пьакета.

* (запись через точку похожа на то, как мы обращались к методам разных *объектов* – списков, строк, но *здесь иначе*: это действительно функции и переменные, а не методы)

In [139]:
max(numbers)

25

In [140]:
numpy.max(numbers)

25

Как правило, инструкцию `import` в случае с `numpy` усложняют, и добавляют сокращённое название пакета (по привычке пишут `np`, это очень распространено):

`import <пакет> as <наш_псевдоним_для_пакета>`

In [9]:
import numpy as np

numbers = [151, 15, 96, 51]
print(np.mean(numbers))
print(np.max(numbers))

78.25
151


### Минимум, максимум, размах

In [13]:
numbers = [9, 1, 2, 8, 6, 4, 3, 7, 5, 10]

print(np.max(numbers))
print(np.min(numbers))

# – запишите выражение для размаха:
# your code here

10
1
9


### Медиана, квартили

In [102]:
np.quantile([1, 2, 3, 4, 5], 0.5)

3.0

In [107]:
sorted(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [105]:
np.quantile(numbers, 0.5)

5.5

In [106]:
np.quantile(numbers, 0.25)

3.25

### Тренировка

Ниже приведён список ростов случайных 100 человек из поликлиники. Найдите:

* средний рост
* медианный рост, 
* отметку роста, выше которой 80% людей
* отметку роста, ниже которой 90% людей
* максимальный рост
* отметку роста, ниже которой 99%

**позже, после `np.array()`**:
* стандартное отклонение ростов

In [121]:
heights = [160, 197, 173, 179, 179, 190, 169, 161, 170, 190, 167, 198, 163, 164, 197, 191, 167, 169, 181,
           174, 179, 191, 163, 196, 169, 181, 171, 182, 187, 160, 186, 164, 193, 190, 178, 179, 169, 170,
           176, 184, 169, 171, 169, 194, 185, 167, 162, 178, 173, 166, 191, 188, 166, 193, 160, 162, 166,
           196, 165, 166, 170, 197, 171, 171, 162, 195, 187, 198, 179, 176, 164, 185, 188, 179, 167, 182,
           171, 185, 171, 177, 197, 186, 194, 168, 167, 180, 188, 169, 170, 176, 166, 184, 173, 192, 175,
           197, 182, 186, 167, 176]

### Мода

Не очень удобно считается..

In [112]:
numbers2 = list(numbers)
numbers2.append(3)
print(numbers2)

uniq, counts = np.unique(numbers2, return_counts=True)

print(uniq)
print(counts)

i_max = np.argmax(counts)
uniq[i_max]

[9, 1, 2, 8, 6, 4, 3, 7, 5, 10, 3]
[ 1  2  3  4  5  6  7  8  9 10]
[1 1 2 1 1 1 1 1 1 1]


3

In [116]:
print(np.bincount(numbers2))

num_max = np.argmax(np.bincount(numbers2))

print(num_max)

[0 1 1 2 1 1 1 1 1 1 1]
3


### 🥰 Массивы `np.array`

#### Создаём массив

In [23]:
arr = np.array(numbers)

print(arr)

[ 9  1  2  8  6  4  3  7  5 10]


In [24]:
print(type(arr)) # массив нампай

<class 'numpy.ndarray'>


#### Действия с массивами

In [7]:
# попробуем сложить два списка
height = [156, 172, 164]  # это рост трёх людей
d = [8, 2, 3]
print(height + d) # выполнилась операция "склейки"

[156, 172, 164, 8, 2, 3]


In [8]:
# попробуем сложить два массива numpy
height_np = np.array(height)
d_np = np.array(d)
print(height_np + d_np)  # выполнилось поэлементное сложение

[164 174 167]


Оказывается, можно делать операции с массивами, и они будут проводиться с каждым числом в массиве, параллельно!

In [9]:
# Все выросли на 2 см - какой теперь рост?
height_np + 2

array([158, 174, 166])

Вернёмся к `arr`

In [25]:
arr ** 2

array([ 81,   1,   4,  64,  36,  16,   9,  49,  25, 100])

In [18]:
arr2 = np.array([31, 5, 63, 8, 9, 17, 56, 9, 13, 77])

print(len(arr2))

10


In [19]:
arr + arr2

array([40,  6, 65, 16, 15, 21, 59, 16, 18, 87])

In [20]:
arr * arr2

array([279,   5, 126,  64,  54,  68, 168,  63,  65, 770])

In [21]:
arr2 - arr

array([22,  4, 61,  0,  3, 13, 53,  2,  8, 67])

Второй массив должен быть той же длины, только тогда можно делать операции поэлементно

In [28]:
arr3 = np.array([31, 5, 63, 8, 9, 17, 56, 9])

print(len(arr3))

8


In [27]:
arr + arr3

ValueError: operands could not be broadcast together with shapes (10,) (8,) 

#### Тренировка

Я загадал несколько чисел. Вам нужно выяснить, что это были за числа, при условии, что я скажу вам...

1. что я прибавил к ним 3, умножил результат на 4 и получил `[16, 20, 24, 28, 32]`
2. что я поделил 60 на эти числа, вычел 10 и умножил результат на 2, и получил `[4.0, 10.0, 20.0, 40.0, 100.0]`
3. что поделил эти числа на 3, вычел 4, поделил на 4, вычел 5 и умножил результат на 2, чтобы получить `[0.0, 4.0, -10.0, 1.5, -1.0]`

#### Логические операции

In [31]:
height_np = np.array([156, 172, 164])

In [32]:
print(height_np > 160) # сравним каждый элемент с 160

[False  True  True]


Это аналогично тому, как арифметические операции делались для одного элемента или для другого массива той же длины!

In [33]:
height_min = np.array([150, 165, 165])
print(height_np > height_min)

[ True  True False]


Вернёмся обратно. Этот булев массив `True`/`False` можно подставить в качестве сложного "индекса" и будет фильтрация (останутся те, где `True`)!

In [14]:
print(height_np[height_np > 160]) # отфильтровали только значения, которые больше 160

[172 164]


In [15]:
age = np.array([18, 19, 20, 4, 12, 21, 48, 32, 85])  # это возрасты людей

In [16]:
age < 18

array([False, False, False,  True,  True, False, False, False, False])

In [17]:
# У кого скидка в музей?
(age < 18) | (age > 75)

array([False, False, False,  True,  True, False, False, False,  True])

In [18]:
age[(age < 18) | (age > 75)]

array([ 4, 12, 85])

**В массиве все элементы одного типа**

In [20]:
z_np = np.array(['cat', 1, 2.4, True])
print(z_np)

['cat' '1' '2.4' 'True']


In [21]:
print(z_np.dtype)
print(type(z_np[2]))  # вот такой тип у каждого элемента

<U32
<class 'numpy.str_'>


In [22]:
z_np = np.array([1, 2.4, True])
print(z_np)
print(z_np.dtype) # целое число и логическое значение превратились во float

[1.  2.4 1. ]
float64


In [23]:
z_np = np.array([1, True])
print(z_np)
print(z_np.dtype) # логическое значение превратилось в integer

[1 1]
int64


In [24]:
z_np = np.array([True]) # и только одинокий True смог остаться сам собой
print(z_np)
print(z_np.dtype)

[ True]
bool


#### Многомерные массивы (матрицы)

In [25]:
# Надо соблюдать размерность!
np.array([[0, 0, 1],
         [0, 1]]) 

/var/folders/91/b5c9lg_s0c9bslz7x5586n040000gp/T/ipykernel_53417/2396008021.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[0, 0, 1],


array([list([0, 0, 1]), list([0, 1])], dtype=object)

In [26]:
tempr = np.array([[7, 6, 13, 11], [7, 6, 12, 11], [6, 6, 10, 8]])

# сегодня, завтра, послезавтра
# ночь, утро, день, вечер
print(tempr)

[[ 7  6 13 11]
 [ 7  6 12 11]
 [ 6  6 10  8]]


In [29]:
print(tempr[0][1]) # выведи значение в первом ряду во второй колонке

6


А ещё с массивами можно вот так:

(осторожно, со списками так нельзя)

In [30]:
print(tempr[0, 1]) # выведи значение в первом ряду во второй колонке

6


In [31]:
print(tempr[:, 1]) # выведи все ряды (:), но только вторую колонку
print(tempr[0, :]) # выведи только первый ряд, но все колонки
print(tempr[0, 1:]) # выведи только первый ряд, только колонки со второй и до конца

[6 6 6]
[ 7  6 13 11]
[ 6 13 11]


#### Тренировка
- Какая температура завтра днём?
- Какая температура послезавтра?
- Какая температура все ближайшие вечера?

In [34]:
# ваш код
print('Завтра днём:', )
print('Послезавтра:', )
print('Вечера:', )

Завтра днём:
Послезавтра:
Вечера:


**Атрибуты и методы**

In [36]:
tempr.size # атрибут — показывает количество элементов в массиве 

12

In [37]:
print(tempr.shape)  # количество строк, количество столбцов

(3, 4)


In [42]:
print(tempr.mean()) # метод() находит среднее арифметическое массива

8.583333333333334


In [40]:
print(tempr.sum() / tempr.size)  # .sum()

8.583333333333334


Напоминание: атрибут после точки без скобок, метод со скобками после точки.

Атрибуты - свойства объекта, подпеременные, в котор хранится

Методы (они же вариант функций) выполняют действия.

### Массивы быстрее списков (эксперимент 1)

Вычислительные операции быстрее выполняются с массивами numpy чем со списками. Давайте создадим два списка из 1000000 чисел и перемножим их.

In [41]:
import time

# задаем размер наших списков
size = 1000000  
   
# объявляем списки
list1 = range(size)
list2 = range(size)

# запоминаем временную метку
initial_time = time.time()
  
# перемножаем элементы списков
result_list = [(a * b) for a, b in zip(list1, list2)]
list_time = time.time() - initial_time

# смотрим, сколько времени это заняло
print("Сколько времени заняло перемножение списков?", list_time, "сек")

Сколько времени заняло перемножение списков? 0.31250619888305664 сек


Теперь проделаем то же с массивами NumPy.

In [42]:
# объявляем массивы numpy
array1 = np.arange(size)  
array2 = np.arange(size)
   
# запоминаем временную метку
initial_time = time.time()
  
# перемножаем массивы
result_array = array1 * array2

array_time = time.time() - initial_time

# смотрим, сколько времени это заняло
print("Сколько времени заняло перемножение массивов numpy?", array_time, "сек.")

Сколько времени заняло перемножение массивов numpy? 0.012279033660888672 сек.


In [43]:
print(round(list_time/array_time))

25


### Специализированные инструменты быстрее (эксперимент 2)

Теперь давайте убедимся, что использовать метод `.sum()` для массивов NumPy предпочтительней, чем функцию `sum()` из стандарной библиотеки Python. Также создадим список из 1000000 чисел и сложим их разными способами.

In [44]:
size = 1000000  
list1 = range(size)
array1 = np.array(list1)

initial_time = time.time()
list_sum = sum(list1) # складываем числа списка Python стандартной функцией
sum1_time = time.time() - initial_time

initial_time = time.time()
array_sum = array1.sum() # складываем числа массива NumPy методом массива
sum2_time = time.time() - initial_time

initial_time = time.time()
array2_sum = sum(array1) # складываем числа массива NumPy стандартной функцией
sum3_time = time.time() - initial_time

print('Находим сумму элементов списка с функцией sum():', sum1_time)
print('Находим сумму элементов массива с нативным методом .sum():', sum2_time)
print('Находим сумму элементов массива с функцией sum():', sum3_time)

Находим сумму элементов списка с функцией sum(): 0.06750178337097168
Находим сумму элементов массива с нативным методом .sum(): 0.0022318363189697266
Находим сумму элементов массива с функцией sum(): 0.36887192726135254


### Установка
<a name="install-numpy"></a>


Если `numpy` оказался не установлен, то скорее всего поможет вот такая команда в ячейке (это просьба к питоновскому менеджеру пакетов `pip` установить `numpy`, а восклицательный знак, потому что это не код на питоне, а обращение к *совсем* внешним программам) 

In [ ]:
!pip install numpy

## Токенизация
***(этого не будет в экзамене)***

"Не для экзамена, а для жизни мы <s>учимся</s> учим питон"

**Natasha** &mdash; библиотека для обработки текстов на естественном русском языке.

Есть много пакетов, которые могут делить текст на предложения.
    Но с русским особенно хорош пакет `razdel` (это часть проекта-библиотеки `natasha`).

In [52]:
# чтобы использовать, надо установить библиотеку
!pip install natasha

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python3.9 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Теперь у нас установлен этот большой набор программ (библиотека `natasha`),
    среди которых наш небольшой пакет для разбиения текстов &mdash; `razdel`.

Но пакет этот нам может быть нужен не каждый раз!
    Например, когда у нас уже есть какая-то статистика по авторам (их годам жизни, количеству произведений с годами публикаций и т.д.),
    нам не нужно разбивать тексты на слова, а нужна простая программа, которая будет что-то считать.
    Поэтому, когда мы прямо хотим воспользоваться в своей программе какой-то другой программой (пакетом / библиотекой), то нам это нужно явно указать.
    Тогда Python поймёт, что внешняя программа понадобится и подключит её *(а если бы не написали этого, то не подключал бы. Экономия!)*.

In [1]:
from razdel import sentenize

Что мы сейчас сделали? Мы сначала установили библиотеку, а потом импортировали из неё нужную нам функцию. Сначала взяли огромную коробку, а потом рассказали программе, что есть функция внутри коробки, которую хочется уметь использовать.

In [5]:
text = "Вот хотим мы поделить текст на предложения. Можно просто поделить по точке. Но что делать, с предложениями, заканчивающимися не на точку? Восклицательные и вопросительные знаки забыли! Как же быть... Проверять все завершающие знаки препинания. А что скажет на это А.С.Пушкин, чьи инициалы содержат точки? Лучше воспользоваться библиотекой, которая умеет делить на предложения! Она и про 0.5 гр. и 100 руб. знает..."

print(sentenize(text))

<generator object find_substrings at 0x0000027941628890>


*(снова печатается непонятно что, как и с `range` и `enumerate`. Помним, что можно поглотить и создать, например, список или пройтись в цикле `for`)*

In [6]:
# А вот так можно посмотреть
list(sentenize(text))

[Substring(0, 43, 'Вот хотим мы поделить текст на предложения.'),
 Substring(44, 75, 'Можно просто поделить по точке.'),
 Substring(76,
           137,
           'Но что делать, с предложениями, заканчивающимися не на точку?'),
 Substring(138, 184, 'Восклицательные и вопросительные знаки забыли!'),
 Substring(185, 199, 'Как же быть...'),
 Substring(200, 243, 'Проверять все завершающие знаки препинания.'),
 Substring(244,
           304,
           'А что скажет на это А.С.Пушкин, чьи инициалы содержат точки?'),
 Substring(305,
           376,
           'Лучше воспользоваться библиотекой, которая умеет делить на предложения!'),
 Substring(377, 414, 'Она и про 0.5 гр. и 100 руб. знает...')]

In [8]:
# Вот так удобнее
for sent in sentenize(text):
    print(sent.text)  # тут нет скобочек, потому что это не совсем действие, просто свойство
                      # но об этом можно не думать

Вот хотим мы поделить текст на предложения.
Можно просто поделить по точке.
Но что делать, с предложениями, заканчивающимися не на точку?
Восклицательные и вопросительные знаки забыли!
Как же быть...
Проверять все завершающие знаки препинания.
А что скажет на это А.С.Пушкин, чьи инициалы содержат точки?
Лучше воспользоваться библиотекой, которая умеет делить на предложения!
Она и про 0.5 гр. и 100 руб. знает...


In [9]:
# Поделим на предложения текст с разными сокращениями
text2 = """Почему я как композитор-оперник тяготею к классике? Это у меня с детства. В детстве я очень любил играть в классики. Ребенком я любил пить чай, естественно, с пирожными, и лучше всего с безе. Отсюда в сублимации ассоциаций детства тяготение к Чайковскому, к Бизе, и т. д., и т. п., и т. д. Как сказал классик, надо брать музыку у народа, и только обрабатывать её. Так я и делаю. Поэтому, когда сегодня берёшь у композитора — это, собственно говоря, берёшь у народа, берёшь у народа — берёшь у себя, и главное, чтобы музыка была твоя, и кто говорит "плагиат", я говорю "традиция"."""

list(sentenize(text2))

[Substring(0, 51, 'Почему я как композитор-оперник тяготею к классике?'),
 Substring(52, 73, 'Это у меня с детства.'),
 Substring(74, 116, 'В детстве я очень любил играть в классики.'),
 Substring(117,
           191,
           'Ребенком я любил пить чай, естественно, с пирожными, и лучше всего с безе.'),
 Substring(192,
           289,
           'Отсюда в сублимации ассоциаций детства тяготение к Чайковскому, к Бизе, и т. д., и т. п., и т. д.'),
 Substring(290,
           363,
           'Как сказал классик, надо брать музыку у народа, и только обрабатывать её.'),
 Substring(364, 378, 'Так я и делаю.'),
 Substring(379,
           579,
           'Поэтому, когда сегодня берёшь у композитора — это, собственно говоря, берёшь у народа, берёшь у народа — берёшь у себя, и главное, чтобы музыка была твоя, и кто говорит "плагиат", я говорю "традиция".')]

In [10]:
# И даже с прямой речью справляется
list(sentenize('''"Привет!" - сказали мы питону.'''))

[Substring(0, 30, '"Привет!" - сказали мы питону.')]

## Теперь делим на слова

Что такое токен? Последовательность символов. (Какая последовательность? Авторы кода определяют для себя это сами.) Обычно это слова в тексте, смайлики, числ в тексте, иногда пунктуация.

Почему бы не сказать, что токен=слово? Потому что "что такое слово?" + числа и пунктуацию сложно назвать словами.

> *Сладострастная отрава - золотая Бричмула,*

> *Где чинара притулилась под скалою, - под скалою...*

> *Про тебя жужжит над ухом вечная пчела:*

> *Бричмула, Бричмулы, Бричмуле, Бричмулу, <span style="color:blue">Бричмулою</span>.*

> *Про тебя жужжит над ухом вечная пчела:*

> *Бричмула, Бричмулы, Бричмуле, Бричмулу, <span style="color:orange">Бричмулою</span>.*

Сколько тут слов - неизвестно. "Бричмула" и "Бричмулы" - разные слова? "<span style="color:blue">Бричмулою</span>" и "<span style="color:orange">Бричмулою</span>" - разные слова?

Это точно разные токены.

In [67]:
from razdel import tokenize

In [60]:
list(tokenize('Мы любим питон. И он нас. Просто нужно познакомиться поближе.'))
# Да, конкретно этот способ сохраняет пунктуацию как отдельные токены
# (можно потом убрать всё, что не буквы)

[Substring(0, 2, 'Мы'),
 Substring(3, 8, 'любим'),
 Substring(9, 14, 'питон'),
 Substring(14, 15, '.'),
 Substring(16, 17, 'И'),
 Substring(18, 20, 'он'),
 Substring(21, 24, 'нас'),
 Substring(24, 25, '.'),
 Substring(26, 32, 'Просто'),
 Substring(33, 38, 'нужно'),
 Substring(39, 52, 'познакомиться'),
 Substring(53, 60, 'поближе'),
 Substring(60, 61, '.')]

In [61]:
punctuation = '''!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~...'''

for token in tokenize('И побольше времени с ним проводить... Привыкнуть.'):
    if token.text not in punctuation:
        print(token.text)

И
побольше
времени
с
ним
проводить
Привыкнуть


In [62]:
# Он справится с:
text5 = "25кг надежды"
list(tokenize(text5)) # Если бы мы делили по пробелам, получили бы слово "25кг "

[Substring(0, 2, '25'), Substring(2, 4, 'кг'), Substring(5, 12, 'надежды')]

In [63]:
text9 = "14ого числа"  # ну вот...
list(tokenize(text9))

[Substring(0, 2, '14'), Substring(2, 5, 'ого'), Substring(6, 11, 'числа')]

In [64]:
list(tokenize("Лежал ли А.С.Пушкин в Санкт-Петербурге на диване-кровати?"))

[Substring(0, 5, 'Лежал'),
 Substring(6, 8, 'ли'),
 Substring(9, 10, 'А'),
 Substring(10, 11, '.'),
 Substring(11, 12, 'С'),
 Substring(12, 13, '.'),
 Substring(13, 19, 'Пушкин'),
 Substring(20, 21, 'в'),
 Substring(22, 38, 'Санкт-Петербурге'),
 Substring(39, 41, 'на'),
 Substring(42, 56, 'диване-кровати'),
 Substring(56, 57, '?')]

In [65]:
list(tokenize("Привет! :)"))

[Substring(0, 6, 'Привет'), Substring(6, 7, '!'), Substring(8, 10, ':)')]

In [66]:
list(tokenize("Смайлики разные: ♥, (о_о), 👨‍👩‍👧‍👦"))

[Substring(0, 8, 'Смайлики'),
 Substring(9, 15, 'разные'),
 Substring(15, 16, ':'),
 Substring(17, 18, '♥'),
 Substring(18, 19, ','),
 Substring(20, 21, '('),
 Substring(21, 24, 'о_о'),
 Substring(24, 25, ')'),
 Substring(25, 26, ','),
 Substring(27, 34, '👨\u200d👩\u200d👧\u200d👦')]